name: CI with Maven and Code Analysis
permissions: write-all

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    name: java pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java

    - name: Build with Maven
      run: mvn -B package --no-transfer-progress --file pom.xml

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 75
        min-coverage-changed-files: 85

    - name: Save Coverage To Environment Variable
      run: |
        echo "TOTAL_COVERAGE=${{ steps.jacoco.outputs.coverage-overall }}" >> $GITHUB_ENV
        echo "CHANGED_FILES_COVERAGE=${{ steps.jacoco.outputs.coverage-changed-files }}" >> $GITHUB_ENV

    - name: Print & Check Coverage Info
      run: |
        import os
        import sys
        print("Total Coverage: " + str(os.environ["TOTAL_COVERAGE"]))
        print("Your Changed Files Coverage: " + str(os.environ["CHANGED_FILES_COVERAGE"]))
        if float(os.environ["TOTAL_COVERAGE"]) < 10 or float(os.environ["CHANGED_FILES_COVERAGE"]) < 10:
          print("Insufficient Coverage!")
          sys.exit(-1)
        sys.exit(0)
      shell: python
   
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
